mydata <- read.csv(file = "Ap.csv")
png("AP.png",width = 400, height = 300)
boxplot(mydata, xlab = "Experient", ylab = "Running time" , outline = F)
dev.off()

mydata <- read.csv(file = "Client.csv")
png("Client.png",width = 400, height = 300)
boxplot(mydata, xlab = "Experient", ylab = "Running time" , outline = F)
dev.off()
mydata <- read.csv(file = "Nodes.csv")
png("Nodes.png",width = 400, height = 300)
boxplot(mydata, xlab = "Experient", ylab = "Running time", outline = F)
dev.off()
mydata <- read.csv(file = "Demand.csv")
png("Demand.png",width = 400, height = 300)
boxplot(mydata, xlab = "Experient", ylab = "Running time", outline = F)
dev.off()
